### PR TITLE
fix linking in Makefile

### LINKED ISSUE #2: can't compile on Debian sid with libevdev-dev 1.8.0
I've tried to compile on Debian sid, here is the result:
```
# make
gcc -Wall -std=c11 -D_POSIX_C_SOURCE=199309L -levdev -I/usr/include/libevdev-1.0 -c uinput.c -o out/uinput.o
gcc -Wall -std=c11 -D_POSIX_C_SOURCE=199309L -levdev -I/usr/include/libevdev-1.0 -c input.c -o out/input.o
gcc -Wall -std=c11 -D_POSIX_C_SOURCE=199309L -levdev -I/usr/include/libevdev-1.0 -c rce.c -o out/rce.o
gcc -Wall -std=c11 -D_POSIX_C_SOURCE=199309L -levdev -I/usr/include/libevdev-1.0 out/uinput.o out/input.o out/rce.o -o out/evdev-rce
/usr/bin/ld: out/uinput.o: in function `uinput_initialize':
uinput.c:(.text+0x9): undefined reference to `libevdev_new'
/usr/bin/ld: uinput.c:(.text+0x20): undefined reference to `libevdev_set_name'
/usr/bin/ld: uinput.c:(.text+0x31): undefined reference to `libevdev_enable_event_type'
/usr/bin/ld: uinput.c:(.text+0x4c): undefined reference to `libevdev_enable_event_code'
/usr/bin/ld: uinput.c:(.text+0x69): undefined reference to `libevdev_uinput_create_from_device'
/usr/bin/ld: uinput.c:(.text+0x81): undefined reference to `libevdev_free'
/usr/bin/ld: out/uinput.o: in function `uinput_send_right_click':
uinput.c:(.text+0xae): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: uinput.c:(.text+0xc9): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: uinput.c:(.text+0xe4): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: uinput.c:(.text+0xff): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: out/input.o: in function `free_evdev':
input.c:(.text+0x14): undefined reference to `libevdev_get_fd'
/usr/bin/ld: input.c:(.text+0x23): undefined reference to `libevdev_free'
/usr/bin/ld: out/input.o: in function `build_fd_set':
input.c:(.text+0xdf): undefined reference to `libevdev_get_fd'
/usr/bin/ld: out/input.o: in function `process_evdev_input':
input.c:(.text+0x4a9): undefined reference to `libevdev_get_fd'
/usr/bin/ld: input.c:(.text+0x4de): undefined reference to `libevdev_get_fd'
/usr/bin/ld: input.c:(.text+0x548): undefined reference to `libevdev_next_event'
/usr/bin/ld: input.c:(.text+0x5c0): undefined reference to `libevdev_uinput_destroy'
/usr/bin/ld: out/rce.o: in function `find_evdev':
rce.c:(.text+0x1ad): undefined reference to `libevdev_new_from_fd'
/usr/bin/ld: rce.c:(.text+0x1fa): undefined reference to `libevdev_has_event_type'
/usr/bin/ld: rce.c:(.text+0x213): undefined reference to `libevdev_has_event_type'
/usr/bin/ld: rce.c:(.text+0x231): undefined reference to `libevdev_has_event_code'
/usr/bin/ld: rce.c:(.text+0x24f): undefined reference to `libevdev_has_event_code'
/usr/bin/ld: rce.c:(.text+0x263): undefined reference to `libevdev_get_name'
/usr/bin/ld: rce.c:(.text+0x346): undefined reference to `libevdev_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: out/evdev-rce] Error 1
```
```
apt policy libevdev-dev
libevdev-dev:
  Installed: 1.8.0+dfsg-2
  Candidate: 1.8.0+dfsg-2
  Version table:
 *** 1.8.0+dfsg-2 500
        500 http://cdn-fastly.deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

### LINKED ISSUE #15: Compile Errors on Raspberry pi 4 running latest Raspbian (Bullseye)
Device: Raspad (Raspberry Pi 4)
Operating System: Raspberry OS (Bullseye)

Hi, I tried to install right click emulation on the latest release of the raspberry pi operating system. I got the compile errors listed below. I installed the emulation in the last release with no problems... Any hints would be appreciated....

gcc -Wall -std=c11 -D_POSIX_C_SOURCE=199309L -levdev -I/usr/include/libevdev-1.0 out/uinput.o out/input.o out/rce.o -o out/evdev-rce
/usr/bin/ld: out/uinput.o: in function `uinput_initialize':
uinput.c:(.text+0xc): undefined reference to `libevdev_new'
/usr/bin/ld: uinput.c:(.text+0x1c): undefined reference to `libevdev_set_name'
/usr/bin/ld: uinput.c:(.text+0x28): undefined reference to `libevdev_enable_event_type'
/usr/bin/ld: uinput.c:(.text+0x3c): undefined reference to `libevdev_enable_event_code'
/usr/bin/ld: uinput.c:(.text+0x58): undefined reference to `libevdev_uinput_create_from_device'
/usr/bin/ld: uinput.c:(.text+0x74): undefined reference to `libevdev_free'
/usr/bin/ld: out/uinput.o: in function `uinput_send_right_click':
uinput.c:(.text+0xb0): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: uinput.c:(.text+0xc4): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: uinput.c:(.text+0xd8): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: uinput.c:(.text+0xec): undefined reference to `libevdev_uinput_write_event'
/usr/bin/ld: out/input.o: in function `free_evdev':
input.c:(.text+0x14): undefined reference to `libevdev_get_fd'
/usr/bin/ld: input.c:(.text+0x20): undefined reference to `libevdev_free'
/usr/bin/ld: out/input.o: in function `build_fd_set':
input.c:(.text+0x110): undefined reference to `libevdev_get_fd'
/usr/bin/ld: out/input.o: in function `process_evdev_input':
input.c:(.text+0x578): undefined reference to `libevdev_get_fd'
/usr/bin/ld: input.c:(.text+0x5bc): undefined reference to `libevdev_get_fd'
/usr/bin/ld: input.c:(.text+0x620): undefined reference to `libevdev_next_event'
/usr/bin/ld: input.c:(.text+0x6a8): undefined reference to `libevdev_uinput_destroy'
/usr/bin/ld: out/rce.o: in function `find_evdev':
rce.c:(.text+0x1a4): undefined reference to `libevdev_new_from_fd'
/usr/bin/ld: rce.c:(.text+0x1f4): undefined reference to `libevdev_has_event_type'
/usr/bin/ld: rce.c:(.text+0x210): undefined reference to `libevdev_has_event_type'
/usr/bin/ld: rce.c:(.text+0x230): undefined reference to `libevdev_has_event_code'
/usr/bin/ld: rce.c:(.text+0x250): undefined reference to `libevdev_has_event_code'
/usr/bin/ld: rce.c:(.text+0x268): undefined reference to `libevdev_get_name'
/usr/bin/ld: rce.c:(.text+0x344): undefined reference to `libevdev_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: out/evdev-rce] Error 1

### PR DESCRIPTION
**Pull request by phd**
gcc parameter -l* must be placed after object files that refer to the libraries' symbols

Fixes #2
Fixes #15

### CODE REVIEW

**Comment by phd** [comment]
Closes #2

**Comment by tbarbette** [comment]
I needed this too

**Review by RIvance — COMMENTED** [review]
works fine on debian 11 with gnu make 4.3 gcc 10.2.1. without this fix will lead to some linking issues

**Comment by phd** [comment]
Fixes #15

**Comment by adcousin** [comment]
Can't thank you enough for this one.

**Comment by pgrawehr** [comment]
@phd Any reason this change is not merged to master?

**Comment by phd** [comment]
> @phd Any reason this change is not merged to master?

No reason other than this repository being abandoned.

**Comment by pgrawehr** [comment]
I see. I just found that it's still useful, though.

**Comment by WhiteBlackGoose** [comment]
Thanks for the fix! Works for me

**Review by bAndie91 — APPROVED** [review]

**Comment by clauber115** [comment]
shame this isn't in main!
